### ISSUE TITLE
Adds CR at the end of all but the last line

### ISSUE THREAD

**Issue by tansongyang** [alimony/sublime-sort-numerically#8] opened 2016-01-30 14:33 UTC
### Environment

* Windows 10
* Sublime Text 3 build 3083
* Most recent version of sublime-sort-numerically

### Steps to reproduce

1. Enter a few lines of numbers, with one number on each line.
2. Use the plugin.

### Results

The numbers are sorted correctly, but an extra `CR` character is also inserted after the number, but before the new line. This happens for all but the last line. For example:

> 1
> 50
> 2.3

becomes

> 1`CR`
> 2.3`CR`
> 50

### Expected

There are no `CR`s inserted.

**Comment by alimony** [comment] 2016-01-30 22:45
Thanks for the report, will have a look at this as soon as possible.

**Comment by olluz** [comment] 2016-02-03 08:57
A workaround for Windows 10 was to edit SortNumerically.py and uncomment the following lines:

`# Determine the current line ending setting, so we can rejoin the`
`# sorted lines using the correct line ending character.`
`line_ending_character = '\n'  # Default.`
`#line_endings = self.view.line_endings()`
`#if line_endings == 'CR':`
`#    line_ending_character = '\r'`
`#elif line_endings == 'Windows':`
`#    line_ending_character = '\r\n'`
`

but this might also break the usage on other platforms.
Just wanted to let you know.

**Comment by alimony** [comment] 2016-02-03 09:39
In the document where you get the incorrect behavior, could you run this in the Sublime console:

    view.line_endings()

What is the result?

**Comment by olluz** [comment] 2016-02-03 10:20
Hi, it is the same as View -> Line endings: Windows

Sent from my HTC

----- Reply message -----

**Comment by alimony** [comment] 2016-02-03 10:30
I wonder if something has changed in Windows 10 so that `\n` is used but the Sublime still reports `Windows`. Could you create a new file, make sure the line ending setting is "Windows", type a few lines, save the file, then open it in some binary editor so we can look at what bytes are actually saved?

**Comment by alimony** [comment] 2016-02-03 10:40
Oh, I see what's going on now. The carriage return character is always displayed as `CR` inside a box. This is how Sublime indicates the hidden char. Since Windows line endings are `CR` followed by a line feed, it will show the hidden char marker too. In other words, this is not the characters C and R, it's just a way to display the hidden carriage return character.

Closing this issue since it's expected behavior.

**Comment by alimony** [comment] 2016-02-03 10:43
Oh wait, that was too fast. I reread the original issue and realized it's still incorrect behavior to suddenly have `CR`s where there were none.

**Comment by alimony** [comment] 2016-02-03 11:19
OK, I've correctly identified why this happens, and after some binary inspection it turns out the line ending setting is only used when storing the bytes on disk, for all other purposes the same line ending char is used internally. I've fixed the behavior in https://github.com/alimony/sublime-sort-numerically/commit/86ebf99563b70f45a8b5cdbf05ab21bbf207a0e6 and will make a new release now.

Thanks again for the report!

**Closed by alimony** 2016-02-03 11:19 UTC

**Comment by alimony** [comment] 2016-02-03 11:20
@tansongyang Would you mind if I add you to the credits list?

**Comment by alimony** [comment] 2016-02-03 13:36
The update is available through Package Control now.

**Comment by tansongyang** [comment] 2016-02-03 18:52
@alimony I've updated and the issue has been fixed. Thanks for the prompt response, and great work on the plugin!

 I'd be honored to accept your offer to be added to the list.

**Comment by alimony** [comment] 2016-02-05 10:59
@tansongyang Done :)
